- name: Listar certificados raíz
  run: |
    echo "Certificados disponibles en sistema:"
    ls /etc/ssl/certs > certificados_root.txt
    echo "Cadena actual usada por certifi:"
    python -m certifi > certifi_path.txt
    cat $(python -m certifi) > certifi_bundle.txt
- name: Subir certificados como artifact
  uses: actions/upload-artifact@v4
  with:
    name: certificados-debug
    path: |
      certificados_root.txt
      certifi_path.txt
      certifi_bundle.txt

name: Agente BCV diario (debuggable)

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 13 * * *'   # 13:00 UTC → 09:00 Venezuela
  workflow_dispatch:

jobs:
  ejecutar-agente:
    runs-on: ubuntu-latest
    env:
      BCV_URL:               ${{ secrets.BCV_URL }}
      TELEGRAM_TOKEN:        ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID:      ${{ secrets.TELEGRAM_CHAT_ID }}
      SMTP_HOST:             ${{ secrets.SMTP_HOST }}
      SMTP_PORT:             ${{ secrets.SMTP_PORT }}
      EMAIL_ORIGEN:          ${{ secrets.EMAIL_ORIGEN }}
      EMAIL_PASS:            ${{ secrets.EMAIL_PASS }}
      ACTIONS_RUNNER_DEBUG:  ${{ secrets.ACTIONS_RUNNER_DEBUG }}
      ACTIONS_STEP_DEBUG:    ${{ secrets.ACTIONS_STEP_DEBUG }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar certificados raíz
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ca-certificates
          pip install --upgrade certifi

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 pandas openpyxl

      - name: Capturar estructura de carpetas
        run: ls -R . > debug_workspace.txt

      - name: Capturar variables de entorno
        run: env | sort > debug_env.txt

      - name: Ejecutar main.py y guardar log
        run: python main.py 2>&1 | tee debug_script.log

      - name: Subir Excel como artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasa_bcv_excel
          path: data/tasa_bcv.xlsx

      - name: Subir archivos de debug
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            debug_workspace.txt
            debug_env.txt
            debug_script.log
