name: Agente BCV diario

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 13 * * *'   # 13:00 UTC → 09:00 Venezuela
  workflow_dispatch:

jobs:
  ejecutar-agente:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 pandas openpyxl

      - name: Ejecutar main.py
        env:
          BCV_URL:        ${{ secrets.BCV_URL }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SMTP_HOST:      ${{ secrets.SMTP_HOST }}
          SMTP_PORT:      ${{ secrets.SMTP_PORT }}
          EMAIL_ORIGEN:   ${{ secrets.EMAIL_ORIGEN }}
          EMAIL_PASS:     ${{ secrets.EMAIL_PASS }}
        run: python main.py

      - name: Subir Excel como artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasa_bcv_excel
          path: data/taxa_bcv.xlsx
