name: Agente BCV diario

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 13 * * *'   # 13:00 UTC → 09:00 Venezuela
  workflow_dispatch:

jobs:
  ejecutar-agente:
    runs-on: ubuntu-latest

    # Carga todos los secrets, incluidos los de debug
    env:
      BCV_URL:               ${{ secrets.BCV_URL }}
      TELEGRAM_TOKEN:        ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID:      ${{ secrets.TELEGRAM_CHAT_ID }}
      SMTP_HOST:             ${{ secrets.SMTP_HOST }}
      SMTP_PORT:             ${{ secrets.SMTP_PORT }}
      EMAIL_ORIGEN:          ${{ secrets.EMAIL_ORIGEN }}
      EMAIL_PASS:            ${{ secrets.EMAIL_PASS }}
      ACTIONS_RUNNER_DEBUG:  ${{ secrets.ACTIONS_RUNNER_DEBUG }}
      ACTIONS_STEP_DEBUG:    ${{ secrets.ACTIONS_STEP_DEBUG }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4 pandas openpyxl

      - name: Ejecutar main.py
        run: python main.py

      - name: Subir Excel como artifact
        uses: actions/upload-artifact@v4
        with:
          name: tasa_bcv_excel
          path: data/tasa_bcv.xlsx
      - name: Subir debug logs
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: home/runner/**
          path: |
            **/home/runner/**

